### ISSUE TITLE
The imgproc module in dataset.py is currently unavailable.

### ISSUE THREAD

**Issue by BaseBlank** [Lornatang/FSRCNN-PyTorch#6]
Hello!
The imgproc module in dataset.py is currently unavailable.
The library imgproc used in dataset.py, the PyPI installation address of this library can be found as follows: https://pypi.org/project/imgproc/#description. 
However, the github warehouse of this library can't be found at present, and it seems that it has been deleted by the developer. The running program will prompt the following error: module' img proc' has no attribute' imresize'.
I really appreciate your works and look forward to your reply, thank you very much!

**Comment by Lornatang** [comment]
imgproc is a py file, it has nothing to do with the library

**Comment by BaseBlank** [comment]
The problem has been solved, and this is my mistake. Thank you very much for your timely reply, and I am very grateful to you again.

**Comment by Lornatang** [comment]
No thanks, the documentation in this library is not detailed enough, you can refer to libraries like SRGAN-PyTorch, which are being updated recently.

**Comment by BaseBlank** [comment]
I will refer and study SRGAN seriously. Thank you very much for your excellent work.
